MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  # WEIGHT: "catalog://ImageNetPretrained/MSRA/R-101"
  # WEIGHT: "/media/liesmars/b71625db-4194-470b-a8ab-2d4cf46f4cdd/Object_detection/FCOS_pytorch/RFCOS/training_dir/84_fovearange_focal_alpha_bg_8_center-muti2_aspectcenter/model_0080000.pth"
  WEIGHT: "/media/liesmars/b71625db-4194-470b-a8ab-2d4cf46f4cdd/Object_detection/FCOS_pytorch/RFCOS/training_dir/105_hrsc_1_class_randomflip_nodiffc_submari_train_val/model_0140000.pth"
 
  RPN_ONLY: True
  FCOS_ON: True
  BACKBONE:
    CONV_BODY: "R-101-FPN-RETINANET" #"R-50-FPN-RETINANET" #
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
    # TRANS_FUNC: "BottleneckWithGN"
  RETINANET:
    USE_C5: False # FCOS uses P5 instead of C5
  FCOS:
    SELECT_FEATURE_METHOD: "foveabox"
    NUM_CLASSES: 2
    NUM_PTS: 1
    LOSS_ALPHA: 0.5 #0.25        0.5
    LOSS_GAMMA: 2.0 #2.0focal   0.  crossentropy
DATASETS:
  TRAIN: ("DOTARotate_2014_train")
  TEST: ("coco_2014_minival",)
INPUT:
  MIN_SIZE_RANGE_TRAIN: (800,800) #(640, 800)
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1333
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.001
  # batch 6 18920
  STEPS: (10000, 20000)
  MAX_ITER: 30000
  IMS_PER_BATCH: 10

  # STEPS: (150000, 180000)
  # MAX_ITER: 200000

  # batch 8
  # STEPS: (40000, 50000)
  # MAX_ITER: 60000

  # batch 10
  # STEPS: (30000, 40000)
  # MAX_ITER: 50000

  # STEPS: (180000, 220000)
  # MAX_ITER: 240000

  # STEPS: (120000, 140000)
  # MAX_ITER: 150000
  # IMS_PER_BATCH: 10
  CHECKPOINT_PERIOD: 5000
  # WARMUP_METHOD: "constant"
