MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-101"
  RPN_ONLY: True
  FCOS_ON: True
  BACKBONE:
    CONV_BODY: "R-101-FPN-RETINANET"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
    # TRANS_FUNC: "BottleneckWithGN"
  RETINANET:
    USE_C5: False # FCOS uses P5 instead of C5
  FCOS:
    SELECT_FEATURE_METHOD: "fcos"
    NUM_CLASSES: 16
    NUM_PTS: 1
DATASETS:
  TRAIN: ("DOTARotate_2014_train")
  TEST: ("coco_2014_minival",)
INPUT:
  MIN_SIZE_RANGE_TRAIN: (800,800) #(640, 800)
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1333
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.001
  # batch 6
  STEPS: (60000, 70000)
  MAX_ITER: 80000
  IMS_PER_BATCH: 6

  # batch 8
  # STEPS: (40000, 50000)
  # MAX_ITER: 60000

  # batch 10
  # STEPS: (30000, 40000)
  # MAX_ITER: 50000

  # STEPS: (180000, 220000)
  # MAX_ITER: 240000
  # IMS_PER_BATCH: 6


  CHECKPOINT_PERIOD: 5000
  # WARMUP_METHOD: "constant"
