MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "/media/liesmars/b71625db-4194-470b-a8ab-2d4cf46f4cdd/Object_detection/FCOS_pytorch/RFCOS/training_dir/location_mutipt/model_final.pth"
  RPN_ONLY: True
  FCOS_ON: True
  BACKBONE:
    CONV_BODY: "R-101-FPN-RETINANET"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  RETINANET:
    USE_C5: False # FCOS uses P5 instead of C5
  FCOS:
    SELECT_FEATURE_METHOD: "fcos"
    NUM_CLASSES: 16
    NUM_PTS: 5
DATASETS:
  TRAIN: ("DOTARotate_2014_train")
  TEST: ("coco_2014_minival",)
INPUT:
  MIN_SIZE_RANGE_TRAIN: (800,800) #(640, 800)
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1333
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.001
  # STEPS: (120000, 160000)
  # MAX_ITER: 180000
  #STEPS: (180000, 220000)
  MAX_ITER: 280000
  IMS_PER_BATCH: 8
  CHECKPOINT_PERIOD: 5000
  # WARMUP_METHOD: "constant"
